- name: Create ServiceNow Change Request
        # ServiceNow/devops-change-request-action 액션 사용
        # 최신 버전 태그를 사용하거나 정확한 버전을 지정합니다.
        uses: rapdev-io/sn-devops-change@v2.0.1
        with:
          # ServiceNow 인스턴스 이름 (예: yourinstance.service-now.com)
          instance-name: 'megazonecloudcorpdemo10'
          # DevOps 연동 사용자 ID
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          # DevOps 연동 사용자 비밀번호
          devops-integration-user-pass: ${{ secrets.SN_DEVOPS_PASSWORD }}
          # Callback을 위한 GitHub 컨텍스트 (자동으로 전달됨)
          context-github: ${{ toJson(github) }}
          # Callback에 사용될 저장소 이름
          callback-repo: ${{ github.repository }}
          # Callback에 사용될 파이프라인 ID (github.run_id)
          callback-pipeline-id: ${{ github.run_id }}
          # 변경 요청에 대한 상세 파라미터 (JSON 형식)
          callback-params: |
            {
              "short_description": "Automated change from GitHub Action for ${{ github.ref_name }}",
              "priority": "3",
              "assignment_group": "My Development Team",
              "justification": "This is a change request created automatically by a GitHub Actions workflow.",
              "implementation_plan": "The changes will be deployed to the target environment."
            }
