name: Create ServiceNow Change on Push

on:
  push:
    branches:
      - main  # main 브랜치에 push 이벤트가 발생했을 때 실행

jobs:
  create_change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ServiceNow Action을 사용하여 변경 요청 생성
      - name: Create ServiceNow Change Request
        uses: ServiceNow/devops-change-request-action@v1.0.0
        with:
          # 필수 입력: ServiceNow 인스턴스 정보와 인증
          sn_instance_url: 'hhttps://megazonecloudcorpdemo10.service-now.com'
          sn_devops_integration_user: ${{ secrets.SN_DEVOPS_USER }}
          sn_devops_integration_password: ${{ secrets.env.SN_DEVOPS_PASSWORD }}

          # 선택적 입력: 생성할 변경 요청의 상세 정보
          short_description: 'Automated change for release from GitHub Actions'
          priority: '2' # 예시: 우선순위 High
          assignment_group: 'Software Development' # 예시: 할당 그룹
          start_date: '2025-08-22 09:00:00' # 변경 시작일
          end_date: '2025-08-25 18:00:00'   # 변경 종료일
          # 기타 변경 레코드 필드를 추가할 수 있습니다.
